# Generated by Django 5.0.4 on 2024-04-25 17:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=240)),
                ('due_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
            ],
        ),
    ]
